In [1]:
import spacy
import numpy as np
import nltk
import re

In [2]:
nlp = spacy.load('es')

In [3]:
with open("pbaspacy.txt", "r") as f:
    corpus = f.read()

In [4]:
# Tokenizing
tokenizer = nltk.data.load('tokenizers/punkt/spanish.pickle')
raw = tokenizer.tokenize(corpus)

In [5]:
print(raw)

['-\n"Lo que sostiene a la pareja es el amor"\nClara Crespo (50) y Rodolfo Martínez (54) no se imaginan uno sin el otro.', '"Prefiero ni pensarlo", dice Clara.', 'Hace 26 años que están casados, y tienen cuatro hijas mujeres.', 'Se conocieron en el Ateneo Juventus, el movimiento juvenil de Capuchinos.', 'Hoy aseguran no estar sorprendidos del tiempo que llevan juntos sino de haber logrado entenderse tan bien.', '&#226;&#8364;&#8220;¿Qué les gusta y disgusta del otro?', '¿Qué quisieran cambiarle?', '&#226;&#8364;&#8220;Rodolfo: Me gusta que sea cariñosa, alegre y esté siempre pensando en mí, y que es una gran madre.', 'Me disgustaba que cuando se enojaba no quería hablar, pero ya no lo hace más.', 'A veces es indecisa pero ya me acostumbré.', 'No quiero cambiarle nada, que sea como es.', '&#226;&#8364;&#8220;Clara : Me gusta que es una persona emprendedora, alegre, optimista y servicial.', 'Me gustaría que a veces fuera más sutil para decir las cosas.', 'Pienso que las personas vamos ca

In [6]:
#limpiando
clean = []
for sent in raw:
    a = re.sub(r'&#\w+;', '', sent)
    b = re.sub(r'[^\w]', ' ', a)
    c = b.rstrip().lstrip()
    clean.append(c)

In [7]:
for i,a in enumerate(clean[:27]):
    print(str(i)+")", a)

0) Lo que sostiene a la pareja es el amor  Clara Crespo  50  y Rodolfo Martínez  54  no se imaginan uno sin el otro
1) Prefiero ni pensarlo   dice Clara
2) Hace 26 años que están casados  y tienen cuatro hijas mujeres
3) Se conocieron en el Ateneo Juventus  el movimiento juvenil de Capuchinos
4) Hoy aseguran no estar sorprendidos del tiempo que llevan juntos sino de haber logrado entenderse tan bien
5) Qué les gusta y disgusta del otro
6) Qué quisieran cambiarle
7) Rodolfo  Me gusta que sea cariñosa  alegre y esté siempre pensando en mí  y que es una gran madre
8) Me disgustaba que cuando se enojaba no quería hablar  pero ya no lo hace más
9) A veces es indecisa pero ya me acostumbré
10) No quiero cambiarle nada  que sea como es
11) Clara   Me gusta que es una persona emprendedora  alegre  optimista y servicial
12) Me gustaría que a veces fuera más sutil para decir las cosas
13) Pienso que las personas vamos cambiando con el tiempo de acuerdo a la edad  a las circunstancias que vivimos

In [8]:
#Para sacar las letras que quedaron colgadas al principio
last_clean = []
for a in clean:
    aux = a.split()
    if len(aux[0]) == 1:
        if aux[0] not in {'A', 'Y', 'O'}:
            del aux[0]
    last_clean.append(aux)

In [9]:
for i,a in enumerate(last_clean[:5]):
    print(str(i)+")", a)

0) ['Lo', 'que', 'sostiene', 'a', 'la', 'pareja', 'es', 'el', 'amor', 'Clara', 'Crespo', '50', 'y', 'Rodolfo', 'Martínez', '54', 'no', 'se', 'imaginan', 'uno', 'sin', 'el', 'otro']
1) ['Prefiero', 'ni', 'pensarlo', 'dice', 'Clara']
2) ['Hace', '26', 'años', 'que', 'están', 'casados', 'y', 'tienen', 'cuatro', 'hijas', 'mujeres']
3) ['Se', 'conocieron', 'en', 'el', 'Ateneo', 'Juventus', 'el', 'movimiento', 'juvenil', 'de', 'Capuchinos']
4) ['Hoy', 'aseguran', 'no', 'estar', 'sorprendidos', 'del', 'tiempo', 'que', 'llevan', 'juntos', 'sino', 'de', 'haber', 'logrado', 'entenderse', 'tan', 'bien']


In [10]:
#flatten list
flat = []
for s in last_clean:
    for w in s:
        flat.append(w)

In [11]:
#Aprovechamos que tenemos una lista de palabras para poder contar su ocurrencia
count = dict()
for w in flat:
    if w not in count:
        count[w] = 1
    else:
        count[w] += 1

In [12]:
#cuantas veces aparece la palabra "el" ? ---> 8
count["Clara"]

5

In [13]:
#Ahora volvemos a unir las palabras a la oración que pertenecen
final = []
for i,s in enumerate(last_clean):
    a = ' '.join(last_clean[i])
    final.append(a)

In [14]:
for i,a in enumerate(final[:27]):
    print(str(i)+")", a)

0) Lo que sostiene a la pareja es el amor Clara Crespo 50 y Rodolfo Martínez 54 no se imaginan uno sin el otro
1) Prefiero ni pensarlo dice Clara
2) Hace 26 años que están casados y tienen cuatro hijas mujeres
3) Se conocieron en el Ateneo Juventus el movimiento juvenil de Capuchinos
4) Hoy aseguran no estar sorprendidos del tiempo que llevan juntos sino de haber logrado entenderse tan bien
5) Qué les gusta y disgusta del otro
6) Qué quisieran cambiarle
7) Rodolfo Me gusta que sea cariñosa alegre y esté siempre pensando en mí y que es una gran madre
8) Me disgustaba que cuando se enojaba no quería hablar pero ya no lo hace más
9) A veces es indecisa pero ya me acostumbré
10) No quiero cambiarle nada que sea como es
11) Clara Me gusta que es una persona emprendedora alegre optimista y servicial
12) Me gustaría que a veces fuera más sutil para decir las cosas
13) Pienso que las personas vamos cambiando con el tiempo de acuerdo a la edad a las circunstancias que vivimos y todo lo que nos 

In [15]:
#Pasamos las oraciones pre-procesadas a Spacy
parsed_sents = []
for doc in nlp.pipe(final, batch_size=10000, n_threads=4):
    parsed_sents.append(doc)

In [16]:
from nltk.corpus import stopwords

In [17]:
parsed_sents[0:5]

[Lo que sostiene a la pareja es el amor Clara Crespo 50 y Rodolfo Martínez 54 no se imaginan uno sin el otro,
 Prefiero ni pensarlo dice Clara,
 Hace 26 años que están casados y tienen cuatro hijas mujeres,
 Se conocieron en el Ateneo Juventus el movimiento juvenil de Capuchinos,
 Hoy aseguran no estar sorprendidos del tiempo que llevan juntos sino de haber logrado entenderse tan bien]

In [18]:
#diccionario con las triplas de cada palabra
dicc_trip = dict()
for s in parsed_sents:
    for w in s:
        tags = [(w.text, w.dep_, w.head.text)]
        if str(w) not in dicc_trip:
            dicc_trip[str(w)] = tags
        else:
            dicc_trip[str(w)] += (tags)

In [19]:
parsed_sents[1]

Prefiero ni pensarlo dice Clara

In [20]:
#lista de listas con tuplas de la forma (palabra, Pos)
pos = []
for s in parsed_sents:
    aux=[]
    for w in s:
        aux.append((w, w.pos_))
    pos.append(aux)

In [21]:
pos[2]

[(Hace, 'AUX'),
 (26, 'NUM'),
 (años, 'NOUN'),
 (que, 'PRON'),
 (están, 'AUX'),
 (casados, 'ADJ'),
 (y, 'CONJ'),
 (tienen, 'VERB'),
 (cuatro, 'NUM'),
 (hijas, 'NOUN'),
 (mujeres, 'ADJ')]

In [22]:
#todas las triplas relacionadas con "el"
dicc_trip["el"]

[('el', 'det', 'amor'),
 ('el', 'det', 'otro'),
 ('el', 'det', 'Ateneo'),
 ('el', 'det', 'movimiento'),
 ('el', 'det', 'tiempo'),
 ('el', 'det', 'momento'),
 ('el', 'det', 'amor'),
 ('el', 'det', 'día')]

In [23]:
for key, value in dicc_trip.items():
    aux = []
    for fst,snd,trd in value:
        a = snd+'.'+trd
        aux.append(a)
        dicc_trip[key] = aux

In [24]:
dicc_trip["el"]

['det.amor',
 'det.otro',
 'det.Ateneo',
 'det.movimiento',
 'det.tiempo',
 'det.momento',
 'det.amor',
 'det.día']

In [25]:
# Lista de etiquetas para cada oración
tag_sents = [[(token.text,token.tag_,token.pos_) for token in parsedEx] for parsedEx in parsed_sents]

In [26]:
# final ---> lista de oraciones procesadas
# tag_sents ---> tags de cada oración
# dep_trips ---> triplas de dep de cada oración

In [27]:
tag_sents[2:4]

[[('Hace',
   'AUX__Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin',
   'AUX'),
  ('26', 'NUM__NumForm=Digit', 'NUM'),
  ('años', 'NOUN__Gender=Masc|Number=Plur', 'NOUN'),
  ('que', 'PRON__PronType=Rel', 'PRON'),
  ('están',
   'AUX__Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin',
   'AUX'),
  ('casados', 'ADJ__Gender=Masc|Number=Plur|VerbForm=Part', 'ADJ'),
  ('y', 'CCONJ___', 'CONJ'),
  ('tienen',
   'VERB__Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin',
   'VERB'),
  ('cuatro', 'NUM__Number=Plur|NumType=Card', 'NUM'),
  ('hijas', 'NOUN__Gender=Fem|Number=Plur', 'NOUN'),
  ('mujeres', 'ADJ__Number=Plur', 'ADJ')],
 [('Se', 'PRON__Person=3', 'PRON'),
  ('conocieron',
   'VERB__Mood=Ind|Number=Plur|Person=3|Tense=Past|VerbForm=Fin',
   'VERB'),
  ('en', 'ADP__AdpType=Prep', 'ADP'),
  ('el', 'DET__Definite=Def|Gender=Masc|Number=Sing|PronType=Art', 'DET'),
  ('Ateneo', 'PROPN___', 'PROPN'),
  ('Juventus', 'PROPN___', 'PROPN'),
  ('el', 'DET__Definite=Def|Gender=Mas

In [30]:
clean_info_word = []
for a in tag_sents:
    for fst,snd,trd in a:
        aux = snd.split("|")
        clean_info_word.append((fst,aux,trd))

In [31]:
#Ahora tenemos una lista de triplas, donde el primer elem es la palabra, el segundo sus tags y el tercero su PoS
print(clean_info_word[0])

('Lo', ['DET__Definite=Def', 'Number=Sing', 'PronType=Art'], 'DET')


In [32]:
pos[2:4]

[[(Hace, 'AUX'),
  (26, 'NUM'),
  (años, 'NOUN'),
  (que, 'PRON'),
  (están, 'AUX'),
  (casados, 'ADJ'),
  (y, 'CONJ'),
  (tienen, 'VERB'),
  (cuatro, 'NUM'),
  (hijas, 'NOUN'),
  (mujeres, 'ADJ')],
 [(Se, 'PRON'),
  (conocieron, 'VERB'),
  (en, 'ADP'),
  (el, 'DET'),
  (Ateneo, 'PROPN'),
  (Juventus, 'PROPN'),
  (el, 'DET'),
  (movimiento, 'NOUN'),
  (juvenil, 'ADJ'),
  (de, 'ADP'),
  (Capuchinos, 'PROPN')]]

In [33]:
from collections import defaultdict
dicc_forward = defaultdict(list)
dicc_backward = defaultdict(list)
for tup in pos:
    for j,(fst,snd) in enumerate(tup):
        if j != 0:
            dicc_backward[fst.text].append((tup[j-1][0].text, tup[j-1][1]))
        else:
            dicc_backward[fst.text].append(("[W.Start]", "[T.Start]"))
        if j != len(tup)-1:
            dicc_forward[fst.text].append((tup[j+1][0].text, tup[j+1][1]))
        else:
            dicc_forward[fst.text].append(("[W.End]", "[T.End]"))

In [34]:
dicc_backward["Clara"]

[('amor', 'NOUN'),
 ('dice', 'VERB'),
 ('[W.Start]', '[T.Start]'),
 ('[W.Start]', '[T.Start]'),
 ('lleva', 'VERB')]

In [35]:
clean_info_word[0]

('Lo', ['DET__Definite=Def', 'Number=Sing', 'PronType=Art'], 'DET')

In [36]:
dicc_forward["Clara"]

[('Crespo', 'PROPN'),
 ('[W.End]', '[T.End]'),
 ('Me', 'PRON'),
 ('asegura', 'VERB'),
 ('[W.End]', '[T.End]')]

In [37]:
lemma_dict = defaultdict(str)
with open('lemmatization-es.txt') as f:
    for line in f:
        splited_line = line.split('\t')
        lemma_dict[splited_line[1].strip()] = splited_line[0]


In [38]:
def lemmatize(word):
   return lemma_dict.get(word, word)

In [39]:
#Creando el diccionario
dicc = dict()
#features = dict()
for fst,snd,trd in clean_info_word:
    features = defaultdict(int)
    pos = 'PoS__' + trd
    if fst.isalpha() and fst not in dicc and count[fst] > 2 and fst not in stopwords.words('spanish'):      #si la palabra es nueva y ocurre mas de n veces -> la agrego
        dicc[lemmatize(fst.lower())] = features
        features[pos] = 1
        for i in snd:
            features[i] = 1
        for i in dicc_trip[fst]:                 #diccionario de triplas
            features[i] = 1
        for i in dicc_backward[fst]:
            features[i[0]+"-1"] += 1
            features[i[1]+"-1"] += 1
        for i in dicc_forward[fst]:
            features[i[0]+"+1"] += 1
            features[i[0]+"+1"] += 1
            
            
    elif fst in dicc:                        #la palabra ya se encuentra -> actualizo el dicc
        has_it = dicc[fst]
        if pos in has_it:
            has_it[pos] += 1
        else:
            has_it[pos] = 1
        for tag in snd:
            if tag in has_it:
                has_it[tag] += 1
            else:
                has_it[tag] = 1
        

In [49]:
dicc_backward["siempre"]

[('esté', 'AUX'), ('y', 'CONJ'), ('crezca', 'VERB')]

In [50]:
dicc_forward["siempre"]

[('pensando', 'VERB'), ('seguiremos', 'AUX'), ('[W.End]', '[T.End]')]

In [51]:
count["siempre"]

3

In [52]:
dicc["siempre"]

defaultdict(int,
            {'ADV___': 3,
             'AUX-1': 1,
             'CONJ-1': 1,
             'PoS__ADV': 3,
             'VERB-1': 1,
             '[W.End]+1': 2,
             'advmod.crezca': 1,
             'advmod.descubriendo': 1,
             'advmod.pensando': 1,
             'crezca-1': 1,
             'esté-1': 1,
             'pensando+1': 2,
             'seguiremos+1': 2,
             'y-1': 1})

In [53]:
#Ahora preparamos la lista una lista de diccs para vectorizar
#Tambien vamos a guardar las palabras que vamos a vectorizar para poder recuperarlas mas tarde
lista_para_vectorizar = []
check_list = []
for key, value in dicc.items():
    check_list.append(key)
    lista_para_vectorizar.append(value)

In [54]:
#Corroboramos la correspondencia
for i,w in enumerate(check_list):
    a = lista_para_vectorizar[i]
    #print(w + " -->", a)

In [66]:
#Vectorizado
from sklearn.feature_extraction import DictVectorizer
v = DictVectorizer(sparse=False)
X = v.fit_transform(lista_para_vectorizar)

In [67]:
X

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  2.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [73]:
#Normalización
import sklearn
X = sklearn.preprocessing.normalize(X)

In [74]:
from sklearn.decomposition import TruncatedSVD

#Reducción de dimensionalidad
svd = TruncatedSVD(n_components=47, n_iter=7, random_state=42)
svd.fit_transform(X)

array([[ 0.3125385 ,  0.17616533,  0.64373017,  0.15536764,  0.27026412,
        -0.14091921, -0.02529048,  0.15409939, -0.37992472,  0.28628365,
         0.21669332,  0.17442547,  0.10171639,  0.03798814],
       [ 0.78389541, -0.0547119 , -0.01144432, -0.26537942, -0.26572353,
        -0.16374699, -0.02347703,  0.07942568, -0.08905999, -0.23971197,
        -0.05884647,  0.06912186, -0.00174435,  0.36611258],
       [ 0.41690619,  0.45200899,  0.08715684,  0.34246447, -0.38648819,
         0.03684221, -0.03138418, -0.30090764, -0.36552191, -0.07341298,
        -0.16697482, -0.21131992, -0.17659084, -0.10964153],
       [ 0.11276682,  0.31965752, -0.08184543,  0.17872348, -0.15906118,
         0.6480133 ,  0.38801248,  0.48869757,  0.01398091, -0.01156151,
         0.05376062, -0.0519029 ,  0.06523493,  0.04113891],
       [ 0.11339639,  0.59641214, -0.41604785, -0.13650545,  0.40522887,
        -0.2158621 ,  0.05429685,  0.15087301,  0.03834683,  0.10484786,
         0.06807831, -0.00

In [75]:
#Clustering
from sklearn.cluster import KMeans
km = KMeans(n_clusters=3)
km.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [76]:
labels = km.predict(X)

In [77]:
print(labels)

[0 1 2 2 2 0 0 2 1 2 1 1 1 1]


In [78]:
#Clusters obtenidos
clusters = defaultdict(set)
for i, label in enumerate(labels):
    clusters[label].add(check_list[i])
print(clusters)

defaultdict(<class 'set'>, {0: {'gustar', 'me', 'el'}, 1: {'do', 'vez', 'amor', 'vida', 'día', 'común'}, 2: {'siempre', 'tan', 'claro', 'coser', 'junto'}})
